welcome_template: "BeautyInsight Agent——人人都能用的数据分析助手"
introduction_template: |
    基于大语言模型（LLM）的对话式数据分析智能体（Agent），它可以理解业务人员用自然语言提出的问题，自动完成数据查询、趋势分析、图表生成和业务总结，真正实现：
    零门槛使用：无需懂代码，只需用“人话”提问即可获得销售走势、用户行为、市场波动等多维度洞察；

    一体化分析体验：从数据处理、指标计算、可视化生成到语言总结，一次对话内流畅完成；

    业务感知智能：自动理解“近3个月”、“核心渠道”、“高活跃客户”等业务表达，并映射为分析参数；

    视觉辅助决策：不仅能说清楚趋势，还能通过动态图表辅助判断变化拐点、节奏异常等现象。

    在欧莱雅真实的订单数据场景中，我们已经实现了基于销售额的趋势分析模块，支持按日、周、月灵活查看趋势曲线，并结合语言大模型自动生成业务解读语句，为非技术人员提供数据驱动的决策支持。